version: '3.8'
services:
  mood-service:
    build: ./mood-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - activemq
      - auth-server

  stats-service:
    build: ./stats-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - activemq
      - db

  activemq:
    image: rmohr/activemq
    ports:
      - "61616:61616"
      - "8161:8161"

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: moodstats
    ports:
      - "5432:5432"

  auth-server:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
    ports:
      - "8080:8080"
